# Generated by Django 5.1.5 on 2025-03-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='servicio',
        ),
    ]
